# Generated by Django 4.1.2 on 2022-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('width', models.DecimalField(decimal_places=5, max_digits=10)),
                ('height', models.DecimalField(decimal_places=5, max_digits=10)),
                ('length', models.DecimalField(decimal_places=5, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
