# Generated by Django 4.1.2 on 2022-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_custumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serviceship',
            field=models.CharField(choices=[('fedex', 'fedex'), ('ups', 'ups')], default='fedex', max_length=10),
        ),
    ]
