# Generated by Django 4.1.2 on 2022-10-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_serviceship_post_serviceshipid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='serviceShipID',
        ),
        migrations.AddField(
            model_name='post',
            name='serviceship',
            field=models.CharField(choices=[('Debt', ((11, 'Credit Card'), (12, 'Student Loans'), (13, 'Taxes'))), ('Entertainment', ((21, 'Books'), (22, 'Games'))), ('Everyday', ((31, 'Groceries'), (32, 'Restaurants')))], default='---', max_length=10),
        ),
    ]
