# Generated by Django 4.1.2 on 2022-10-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_post_serviceshipid_post_serviceship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='serviceship',
            field=models.CharField(choices=[('FedEx service', ((1, 'fedexAIR'), (2, 'fedexGroud'))), ('UPS service', ((3, 'UPSExpress'), (4, 'UPS2DAY')))], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
